/**
 * KI-Prime — Public Intake Routes
 *
 * These endpoints are intentionally unauthenticated — they are accessed
 * by the contact/lead via a signed intake token URL. Auth is the token itself.
 *
 * POST /api/v1/intake/validate  — validate token, return pre-fill + brand data (v2)
 * POST /api/v1/intake/submit    — submit filled snapshot (creates/updates contact)
 *
 * Security model:
 *   - Token is 32-byte cryptographically random hex (generated by generate_intake_token)
 *   - Token is single-use: status changes to 'used' on submit
 *   - Token expires after 5 days
 *   - Tenant context is derived from the token row — never from the request body
 *   - All tenant_id isolation is enforced by looking up the token in DB
 */

import { Router } from 'express';
import * as fs from 'fs';
import * as path from 'path';
import type { Pool } from 'pg';
import { translateParams } from '../db/query';

const VALIDATE_SQL = fs.readFileSync(
  path.join(__dirname, '../skills/contact-skill/queries/validate-intake-token.sql'), 'utf-8'
);

const ASSET_TYPES_SQL = `
  SELECT id, asset_type_code AS code, asset_type_name AS label, is_liquid_default
  FROM ki_asset_types
  WHERE is_active = true
  ORDER BY display_order, asset_type_name;
`;

const LIABILITY_TYPES_SQL = `
  SELECT id, code, label
  FROM ki_liability_types
  ORDER BY sort_order, label;
`;

export function createIntakeRouter(pool: Pool): Router {
  const router = Router();

  /* ── POST /validate ─────────────────────────────────── */

  router.post('/validate', async (req, res) => {
    const { token } = req.body as { token?: string };

    if (!token || typeof token !== 'string' || token.length !== 64) {
      res.status(400).json({ error: { code: 'INVALID_TOKEN', message: 'Invalid token format' } });
      return;
    }

    let client;
    try {
      client = await pool.connect();
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      console.error('[Intake:validate] DB connect failed:', msg);
      res.status(503).json({
        error: {
          code: 'DB_UNAVAILABLE',
          message: 'Database connection failed',
          ...(process.env.NODE_ENV !== 'production' && { detail: msg }),
        },
      });
      return;
    }

    try {
      // Look up token
      const { text, values } = translateParams(VALIDATE_SQL, { $token: token });
      const result = await client.query(text, values);

      if (result.rows.length === 0) {
        res.status(404).json({ error: { code: 'TOKEN_NOT_FOUND', message: 'Link is invalid, expired, or already used' } });
        return;
      }

      const row = result.rows[0];

      // Load master data (global tables — no tenant filter)
      const [assetRes, liabRes] = await Promise.all([
        client.query(ASSET_TYPES_SQL),
        client.query(LIABILITY_TYPES_SQL),
      ]);

      const flow = row.contact_id ? 'known_contact' : 'cold_lead';

      res.json({
        token_id:   row.token_id,
        flow,
        tenant: {
          display_name: row.tenant_display_name || row.tenant_name,
          brand_color:  row.brand_color || null,
          theme_id:     row.theme_id || null,
        },
        mfd_name:   row.mfd_name || null,
        expires_at: row.expires_at,
        contact_prefill: flow === 'known_contact' ? {
          prefix: row.contact_prefix || '',
          name:   row.contact_name   || '',
          mobile: row.contact_mobile || '',
          email:  row.contact_email  || '',
        } : null,
        asset_types:     assetRes.rows,
        liability_types: liabRes.rows,
      });
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      console.error('[Intake:validate]', msg);
      res.status(500).json({
        error: {
          code: 'INTERNAL_ERROR',
          message: 'Validation failed',
          ...(process.env.NODE_ENV !== 'production' && { detail: msg }),
        },
      });
    } finally {
      client.release();
    }
  });

  /* ── POST /submit ───────────────────────────────────── */

  router.post('/submit', async (req, res) => {
    const {
      token,
      // Flow 2 lead capture
      lead_name, lead_mobile, lead_email,
      // Snapshot sections
      income = [], expenses = [], assets = [], liabilities = [],
      protection = {}, goals = [],
      risk_profile, notes,
    } = req.body as Record<string, unknown> & { token?: string };

    if (!token || typeof token !== 'string' || token.length !== 64) {
      res.status(400).json({ error: { code: 'INVALID_TOKEN', message: 'Invalid token format' } });
      return;
    }

    const client = await pool.connect();
    try {
      await client.query('BEGIN');

      // Re-validate token (status='active', not expired)
      const { text: vText, values: vVals } = translateParams(VALIDATE_SQL, { $token: token });
      const tokenRes = await client.query(vText, vVals);
      if (tokenRes.rows.length === 0) {
        await client.query('ROLLBACK');
        res.status(404).json({ error: { code: 'TOKEN_NOT_FOUND', message: 'Link is invalid, expired, or already used' } });
        return;
      }
      const tokenRow = tokenRes.rows[0];
      const tenantId  = tokenRow.tenant_id as string;
      const tokenId   = tokenRow.token_id  as number;
      const flow      = tokenRow.contact_id ? 'known_contact' : 'cold_lead';

      // Set tenant RLS context
      await client.query(`SELECT set_config('app.current_tenant_id', $1, true)`, [tenantId]);

      let contactId: number = tokenRow.contact_id;

      // ── Flow 2: create contact from lead data ──────────────
      if (flow === 'cold_lead') {
        const nameVal   = String(lead_name   || '').trim();
        const mobileVal = String(lead_mobile || '').trim();
        const emailVal  = String(lead_email  || '').trim();

        if (!nameVal) {
          await client.query('ROLLBACK');
          res.status(400).json({ error: { code: 'VALIDATION_ERROR', message: 'Name is required' } });
          return;
        }

        // Insert contact — prefix NOT NULL with CHECK; use 'Mr' as default for cold leads
        // normalized_name is GENERATED ALWAYS AS — must not be in INSERT column list
        const contactInsert = await client.query(
          `INSERT INTO ki_contacts (tenant_id, name, prefix, is_client, is_active, is_live)
           VALUES ($1, $2, 'Mr', false, true, false)
           RETURNING id`,
          [tenantId, nameVal]
        );
        contactId = contactInsert.rows[0].id;

        // Insert channels
        if (mobileVal) {
          await client.query(
            `INSERT INTO ki_contact_channels (tenant_id, contact_id, channel_type, channel_value, channel_subtype, is_primary, is_active)
             VALUES ($1, $2, 'mobile', $3, 'personal', true, true)`,
            [tenantId, contactId, mobileVal]
          );
        }
        if (emailVal) {
          await client.query(
            `INSERT INTO ki_contact_channels (tenant_id, contact_id, channel_type, channel_value, channel_subtype, is_primary, is_active)
             VALUES ($1, $2, 'email', $3, 'personal', $4, true)`,
            [tenantId, contactId, emailVal, !mobileVal]
          );
        }

        // Store lead data in token row
        await client.query(
          `UPDATE ki_intake_tokens
           SET lead_name = $1, lead_mobile = $2, lead_email = $3, contact_id = $4
           WHERE id = $5`,
          [nameVal, mobileVal || null, emailVal || null, contactId, tokenId]
        );
      }

      // ── Resolve next version number ────────────────────────
      const versionRes = await client.query(
        `SELECT COALESCE(MAX(version_number), 0) + 1 AS next_version
         FROM ki_contact_snapshots
         WHERE contact_id = $1 AND tenant_id = $2`,
        [contactId, tenantId]
      );
      const versionNumber = versionRes.rows[0].next_version as number;

      // ── Archive any existing active snapshot ───────────────
      await client.query(
        `UPDATE ki_contact_snapshots
         SET status = 'archived'
         WHERE contact_id = $1 AND tenant_id = $2 AND is_live = false AND status = 'active'`,
        [contactId, tenantId]
      );

      // ── Compute calc_ metrics ──────────────────────────────
      const incomeArr  = income  as Array<{ source: string; amount_monthly: number }>;
      const expenseArr = expenses as Array<{ category: string; amount_monthly: number }>;
      const assetArr   = assets  as Array<{ current_value: number; is_liquid: boolean }>;
      const liabArr    = liabilities as Array<{ outstanding_amount: number; monthly_emi: number }>;
      const protObj    = protection as Record<string, number | boolean>;

      const monthlyIncome   = incomeArr.reduce((s, r) => s + (Number(r.amount_monthly) || 0), 0);
      const monthlyExpenses = expenseArr.reduce((s, r) => s + (Number(r.amount_monthly) || 0), 0);
      const totalAssets     = assetArr.reduce((s, r) => s + (Number(r.current_value)    || 0), 0);
      const totalLiabs      = liabArr.reduce((s, r) => s + (Number(r.outstanding_amount)|| 0), 0);
      const netWorth        = totalAssets - totalLiabs;
      const totalEmi        = liabArr.reduce((s, r) => s + (Number(r.monthly_emi)       || 0), 0);
      const liquidAssets    = assetArr.filter(a => a.is_liquid).reduce((s, r) => s + (Number(r.current_value) || 0), 0);

      const savingsRatePct    = monthlyIncome > 0 ? ((monthlyIncome - monthlyExpenses) / monthlyIncome) * 100 : null;
      const dtiPct            = monthlyIncome > 0 ? (totalEmi / monthlyIncome) * 100 : null;
      const liquidityMonths   = monthlyExpenses > 0 ? liquidAssets / monthlyExpenses : null;
      const lifeCover         = Number(protObj.life_cover_amount) || null;
      const protectionRatioPct = lifeCover && monthlyIncome > 0 ? (lifeCover / (monthlyIncome * 12)) * 100 : null;

      // ── Insert snapshot header ──────────────────────────────
      const snapInsert = await client.query(
        `INSERT INTO ki_contact_snapshots
           (tenant_id, contact_id, is_live, version_number, status,
            created_by_user_id, intake_token_id, risk_profile, notes, submitted_at,
            calc_monthly_income, calc_monthly_expenses, calc_monthly_savings,
            calc_savings_rate_pct, calc_total_assets, calc_total_liabilities,
            calc_net_worth, calc_total_emi, calc_dti_pct,
            calc_liquid_assets, calc_liquidity_months, calc_protection_ratio_pct)
         VALUES
           ($1, $2, false, $3, 'active',
            NULL, $4, $5, $6, now(),
            $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
         RETURNING id`,
        [
          tenantId, contactId, versionNumber, tokenId,
          risk_profile || null, notes || null,
          monthlyIncome, monthlyExpenses, monthlyIncome - monthlyExpenses,
          savingsRatePct, totalAssets, totalLiabs, netWorth,
          totalEmi, dtiPct, liquidAssets, liquidityMonths, protectionRatioPct,
        ]
      );
      const snapshotId = snapInsert.rows[0].id as number;

      // ── Insert child rows ───────────────────────────────────
      for (const row of incomeArr.filter(r => Number(r.amount_monthly) > 0)) {
        await client.query(
          `INSERT INTO ki_snapshot_income (snapshot_id, source, amount_monthly, notes)
           VALUES ($1, $2, $3, $4)`,
          [snapshotId, row.source, Number(row.amount_monthly), (row as Record<string, unknown>).notes || null]
        );
      }

      for (const row of expenseArr.filter(r => Number(r.amount_monthly) > 0)) {
        await client.query(
          `INSERT INTO ki_snapshot_expenses (snapshot_id, category, amount_monthly)
           VALUES ($1, $2, $3)`,
          [snapshotId, row.category, Number(row.amount_monthly)]
        );
      }

      const assetArrFull = assets as Array<Record<string, unknown>>;
      for (let i = 0; i < assetArrFull.length; i++) {
        const a = assetArrFull[i];
        if (!Number(a.current_value)) continue;
        await client.query(
          `INSERT INTO ki_snapshot_assets
             (snapshot_id, asset_type_id, description, current_value, is_liquid, sort_order)
           VALUES ($1, $2, $3, $4, $5, $6)`,
          [snapshotId, Number(a.asset_type_id), a.description || null, Number(a.current_value), Boolean(a.is_liquid), i + 1]
        );
      }

      const liabArrFull = liabilities as Array<Record<string, unknown>>;
      for (let i = 0; i < liabArrFull.length; i++) {
        const l = liabArrFull[i];
        if (!Number(l.outstanding_amount)) continue;
        await client.query(
          `INSERT INTO ki_snapshot_liabilities
             (snapshot_id, liability_type_id, description, outstanding_amount, monthly_emi, interest_rate_pct, sort_order)
           VALUES ($1, $2, $3, $4, $5, $6, $7)`,
          [snapshotId, Number(l.liability_type_id), l.description || null,
           Number(l.outstanding_amount), Number(l.monthly_emi) || 0,
           Number(l.interest_rate_pct) || null, i + 1]
        );
      }

      const prot = protection as Record<string, unknown>;
      if (Object.values(prot).some(v => v)) {
        const healthCoverType = String(prot.health_cover_type || '');
        const validCoverTypes = ['individual', 'family_floater', 'employer', 'none'];
        await client.query(
          `INSERT INTO ki_snapshot_protection
             (snapshot_id, life_cover_amount, health_cover_amount, ci_cover_amount,
              life_premium_annual, health_premium_annual, has_term_plan, has_health_cover,
              protection_ratio_pct, health_cover_type)
           VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)`,
          [snapshotId,
           Number(prot.life_cover_amount)   || null,
           Number(prot.health_cover_amount) || null,
           Number(prot.ci_cover_amount)     || null,
           Number(prot.life_premium_annual) || null,
           Number(prot.health_premium_annual) || null,
           Boolean(prot.has_term_plan),
           Boolean(prot.has_health_cover),
           protectionRatioPct,
           validCoverTypes.includes(healthCoverType) ? healthCoverType : null]
        );
      }

      const goalsArr = goals as Array<Record<string, unknown>>;
      for (let i = 0; i < goalsArr.length; i++) {
        const g = goalsArr[i];
        if (!g.name || !Number(g.target_amount)) continue;
        await client.query(
          `INSERT INTO ki_snapshot_goals
             (snapshot_id, goal_type, name, target_amount, timeline_years, priority, sort_order)
           VALUES ($1, $2, $3, $4, $5, $6, $7)`,
          [snapshotId, g.goal_type || 'custom', g.name,
           Number(g.target_amount), Number(g.timeline_years) || 10, i + 1, i + 1]
        );
      }

      // ── Mark token as used ──────────────────────────────────
      await client.query(
        `UPDATE ki_intake_tokens SET status = 'used', used_at = now() WHERE id = $1`,
        [tokenId]
      );

      await client.query('COMMIT');

      res.json({ success: true, contact_id: contactId, snapshot_id: snapshotId });
    } catch (err) {
      await client.query('ROLLBACK').catch(() => {});
      console.error('[Intake:submit]', err);
      res.status(500).json({ error: { code: 'INTERNAL_ERROR', message: 'Submission failed' } });
    } finally {
      client.release();
    }
  });

  return router;
}
