/** The Failure Review & Corrective Action Plan downloads — reference failure.js `failureText`, `failureHTML`, verbatim. */
import { escapeHTML as e } from './model';
import type { Mission } from './types';

export function failureText(m: Mission): string {
  const f = m.failure;
  return `VANI EDGE — FAILURE REVIEW & CORRECTIVE ACTION PLAN\nPRELIMINARY: user-recorded evidence; no independent log analysis or cause validation.\n${m.company} / ${m.process.toUpperCase()}\nRespondent: ${m.respondent.name}\n\nINCIDENT\n${JSON.stringify(f.incident, null, 2)}\n\nDECLARED PROCESS\n${m.board.map((n) => n.label + ' | ' + n.actor + ' | ' + n.system).join('\n')}\n\nCONNECTIONS\n${m.links.map((l) => (m.board.find((n) => n.id === l.from)?.label || l.from) + ' → ' + (m.board.find((n) => n.id === l.to)?.label || l.to) + ' | ' + l.label).join('\n')}\n\nRULES\n${JSON.stringify(m.rules, null, 2)}\n\nEVIDENCE INVENTORY\n${m.files.map((x) => x.name + ' | ' + (x.error || 'File summary only')).join('\n')}\n\nCASE COMPARISON\n${JSON.stringify(f.comparison, null, 2)}\n\nHYPOTHESES\n${JSON.stringify(f.hypotheses, null, 2)}\n\nCORRECTIVE ACTION REGISTER\n${JSON.stringify(f.actions, null, 2)}\n\nVERIFICATION AND RESTART CONDITIONS\n${JSON.stringify(f.verification, null, 2)}\n\nImplementation is not verified effectiveness. Operational restart requires the authorised owner's decision. No production action or report dispatch has been performed.\n`;
}

export function failureHTML(m: Mission): string {
  const f = m.failure;
  const fields = (o: Record<string, unknown>) => `<dl>${Object.entries(o).filter(([k]) => k !== 'id').map(([k, v]) => `<dt>${e(k)}</dt><dd>${e(v || 'Not recorded')}</dd>`).join('')}</dl>`;
  return `<!doctype html><html lang="en"><meta charset="utf-8"><title>Failure Review — ${e(m.company)}</title><style>body{font:15px/1.7 system-ui;max-width:1000px;margin:40px auto;padding:20px;color:#173e31}h2{border-top:1px solid #cad9cd;padding-top:20px}article{border:1px solid #cad9cd;padding:20px;margin:16px 0;border-radius:12px}dt{font-weight:650;text-transform:capitalize}dd{margin:3px 0 14px;white-space:pre-wrap}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:12px/1.6 system-ui}.notice{background:#edf2e8;padding:16px}@media print{button{display:none}h2,h3{break-after:avoid}}</style><button onclick="window.print()">Print / save as PDF</button><p>VANI EDGE / ${e(m.company)} / ${m.process.toUpperCase()}</p><h1>Failure Review & Corrective Action Plan</h1><div class="notice">Preliminary investigation. User-recorded evidence and reviewer judgments; independent log analysis and cause validation are not connected.</div><h2>Executive summary</h2><p>${e(f.incident.title || 'Incident title not recorded')}</p><p>${f.hypotheses.length} possible explanations; ${f.actions.length} corrective actions; ${f.actions.filter((a) => a.status !== 'Effective').length} actions not verified effective.</p><h2>Incident, scope and impact</h2>${fields(f.incident)}<h2>Affected versus successful case</h2>${fields(f.comparison)}<h2>Possible causes and evidence</h2>${f.hypotheses.map((h) => `<article><h3>${e(h.statement)}</h3>${fields(h as unknown as Record<string, unknown>)}</article>`).join('') || '<p>No cause established.</p>'}<h2>Corrective action plan</h2>${f.actions.map((a) => `<article><h3>${e(a.title)}</h3>${fields(a as unknown as Record<string, unknown>)}</article>`).join('') || '<p>No actions recorded.</p>'}<h2>Verification and restart conditions</h2>${fields(f.verification)}<p>Implemented does not mean effective. Operational restart requires the authorised owner’s approval.</p><h2>Process and evidence appendix</h2><pre>${e(failureText(m))}</pre></html>`;
}
