INSERT INTO gt_tenant_profile (
  tenant_id,
  product_name,
  product_tagline,
  product_category,
  product_description,
  core_problem,
  key_differentiators,
  pricing_model,
  pricing_range,
  icp_role,
  icp_company_type,
  icp_company_size,
  icp_industry,
  icp_geography,
  primary_pain_points,
  gtm_stage,
  active_channels,
  current_mrr,
  team_size,
  vision_statement,
  target_market_size,
  completion_score,
  completion_detail,
  source
)
VALUES (
  $tenant_id,
  $product_name,
  $product_tagline,
  $product_category,
  $product_description,
  $core_problem,
  $key_differentiators,
  $pricing_model,
  $pricing_range,
  $icp_role,
  $icp_company_type,
  $icp_company_size,
  $icp_industry,
  $icp_geography,
  $primary_pain_points,
  $gtm_stage,
  $active_channels,
  $current_mrr,
  $team_size,
  $vision_statement,
  $target_market_size,
  $completion_score,
  $completion_detail,
  $source
)
ON CONFLICT (tenant_id) DO UPDATE SET
  product_name        = COALESCE(EXCLUDED.product_name,        gt_tenant_profile.product_name),
  product_tagline     = COALESCE(EXCLUDED.product_tagline,     gt_tenant_profile.product_tagline),
  product_category    = COALESCE(EXCLUDED.product_category,    gt_tenant_profile.product_category),
  product_description = COALESCE(EXCLUDED.product_description, gt_tenant_profile.product_description),
  core_problem        = COALESCE(EXCLUDED.core_problem,        gt_tenant_profile.core_problem),
  key_differentiators = COALESCE(EXCLUDED.key_differentiators, gt_tenant_profile.key_differentiators),
  pricing_model       = COALESCE(EXCLUDED.pricing_model,       gt_tenant_profile.pricing_model),
  pricing_range       = COALESCE(EXCLUDED.pricing_range,       gt_tenant_profile.pricing_range),
  icp_role            = COALESCE(EXCLUDED.icp_role,            gt_tenant_profile.icp_role),
  icp_company_type    = COALESCE(EXCLUDED.icp_company_type,    gt_tenant_profile.icp_company_type),
  icp_company_size    = COALESCE(EXCLUDED.icp_company_size,    gt_tenant_profile.icp_company_size),
  icp_industry        = COALESCE(EXCLUDED.icp_industry,        gt_tenant_profile.icp_industry),
  icp_geography       = COALESCE(EXCLUDED.icp_geography,       gt_tenant_profile.icp_geography),
  primary_pain_points = COALESCE(EXCLUDED.primary_pain_points, gt_tenant_profile.primary_pain_points),
  gtm_stage           = COALESCE(EXCLUDED.gtm_stage,           gt_tenant_profile.gtm_stage),
  active_channels     = COALESCE(EXCLUDED.active_channels,     gt_tenant_profile.active_channels),
  current_mrr         = COALESCE(EXCLUDED.current_mrr,         gt_tenant_profile.current_mrr),
  team_size           = COALESCE(EXCLUDED.team_size,           gt_tenant_profile.team_size),
  vision_statement    = COALESCE(EXCLUDED.vision_statement,    gt_tenant_profile.vision_statement),
  target_market_size  = COALESCE(EXCLUDED.target_market_size,  gt_tenant_profile.target_market_size),
  completion_score    = EXCLUDED.completion_score,
  completion_detail   = EXCLUDED.completion_detail,
  source              = EXCLUDED.source,
  version             = gt_tenant_profile.version + 1,
  updated_at          = NOW()
RETURNING *;
