module.exports = [
"[project]/src/config/theme/ThemeProvider.tsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "ThemeProvider",
    ()=>ThemeProvider,
    "useTheme",
    ()=>useTheme
]);
// This file is generated by next-core EcmascriptClientReferenceModule.
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const ThemeProvider = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call ThemeProvider() from the server but ThemeProvider is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/config/theme/ThemeProvider.tsx <module evaluation>", "ThemeProvider");
const useTheme = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call useTheme() from the server but useTheme is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/config/theme/ThemeProvider.tsx <module evaluation>", "useTheme");
}),
"[project]/src/config/theme/ThemeProvider.tsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "ThemeProvider",
    ()=>ThemeProvider,
    "useTheme",
    ()=>useTheme
]);
// This file is generated by next-core EcmascriptClientReferenceModule.
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const ThemeProvider = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call ThemeProvider() from the server but ThemeProvider is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/config/theme/ThemeProvider.tsx", "ThemeProvider");
const useTheme = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call useTheme() from the server but useTheme is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/config/theme/ThemeProvider.tsx", "useTheme");
}),
"[project]/src/config/theme/ThemeProvider.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$config$2f$theme$2f$ThemeProvider$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/src/config/theme/ThemeProvider.tsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$config$2f$theme$2f$ThemeProvider$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/src/config/theme/ThemeProvider.tsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$config$2f$theme$2f$ThemeProvider$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/src/config/theme/themes/bharathavarshaTheme.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "BharathaVarshaTheme",
    ()=>BharathaVarshaTheme
]);
const BharathaVarshaTheme = {
    id: 'bharathavarsha',
    name: 'Bharathavarsha',
    colors: {
        brand: {
            primary: '#e67e22',
            secondary: '#d35400',
            tertiary: '#8e44ad',
            alternate: '#f39c12'
        },
        utility: {
            primaryText: '#2c3e50',
            secondaryText: '#7f8c8d',
            primaryBackground: '#f9f5f0',
            secondaryBackground: '#ffffff'
        },
        accent: {
            accent1: '#4ce67e22',
            accent2: '#4cd35400',
            accent3: '#4c8e44ad',
            accent4: '#b2ffffff'
        },
        semantic: {
            success: '#27ae60',
            error: '#e74c3c',
            warning: '#f1c40f',
            info: '#3498db'
        },
        surface: {
            glass: 'rgba(0,0,0,0.03)',
            glassStrong: 'rgba(0,0,0,0.05)',
            glassBorder: 'rgba(0,0,0,0.08)',
            primaryDim: 'rgba(230,126,34,0.35)',
            primaryGlow: 'rgba(230,126,34,0.1)',
            primarySubtle: 'rgba(230,126,34,0.04)'
        }
    },
    darkMode: {
        colors: {
            brand: {
                primary: '#e67e22',
                secondary: '#d35400',
                tertiary: '#8e44ad',
                alternate: '#f39c12'
            },
            utility: {
                primaryText: '#ecf0f1',
                secondaryText: '#bdc3c7',
                primaryBackground: '#2c3e50',
                secondaryBackground: '#34495e'
            },
            accent: {
                accent1: '#4ce67e22',
                accent2: '#4cd35400',
                accent3: '#4c8e44ad',
                accent4: '#b2f39c12'
            },
            semantic: {
                success: '#2ecc71',
                error: '#e74c3c',
                warning: '#f1c40f',
                info: '#3498db'
            },
            surface: {
                glass: 'rgba(255,255,255,0.04)',
                glassStrong: 'rgba(255,255,255,0.07)',
                glassBorder: 'rgba(255,255,255,0.08)',
                primaryDim: 'rgba(230,126,34,0.4)',
                primaryGlow: 'rgba(230,126,34,0.15)',
                primarySubtle: 'rgba(230,126,34,0.06)'
            }
        }
    }
};
}),
"[project]/src/config/theme/themes/classicElegantTheme.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "ClassicElegantTheme",
    ()=>ClassicElegantTheme
]);
const ClassicElegantTheme = {
    id: 'classic-elegant',
    name: 'Classic & Elegant',
    colors: {
        brand: {
            primary: '#4b998c',
            secondary: '#928163',
            tertiary: '#c6604a',
            alternate: '#c587c4'
        },
        utility: {
            primaryText: '#0b191e',
            secondaryText: '#384e58',
            primaryBackground: '#f1f4f8',
            secondaryBackground: '#ffffff'
        },
        accent: {
            accent1: '#444b598c',
            accent2: '#445f28163',
            accent3: '#4c6d604a',
            accent4: '#cfffffff'
        },
        semantic: {
            success: '#336a4a',
            error: '#c4454d',
            warning: '#f3c344',
            info: '#ffffff'
        },
        surface: {
            glass: 'rgba(0,0,0,0.03)',
            glassStrong: 'rgba(0,0,0,0.05)',
            glassBorder: 'rgba(0,0,0,0.08)',
            primaryDim: 'rgba(75,153,140,0.35)',
            primaryGlow: 'rgba(75,153,140,0.1)',
            primarySubtle: 'rgba(75,153,140,0.04)'
        }
    },
    darkMode: {
        colors: {
            brand: {
                primary: '#4b496cc',
                secondary: '#928163',
                tertiary: '#c6604a',
                alternate: '#7282e'
            },
            utility: {
                primaryText: '#ffffff',
                secondaryText: '#95a1ac',
                primaryBackground: '#0b191e',
                secondaryBackground: '#131f24'
            },
            accent: {
                accent1: '#44db986c',
                accent2: '#4d928163',
                accent3: '#dc6d004a',
                accent4: '#b20cb7be'
            },
            semantic: {
                success: '#336ada',
                error: '#c4454d',
                warning: '#f3c344',
                info: '#ffffff'
            },
            surface: {
                glass: 'rgba(255,255,255,0.04)',
                glassStrong: 'rgba(255,255,255,0.07)',
                glassBorder: 'rgba(255,255,255,0.08)',
                primaryDim: 'rgba(75,153,140,0.4)',
                primaryGlow: 'rgba(75,153,140,0.15)',
                primarySubtle: 'rgba(75,153,140,0.06)'
            }
        }
    }
};
}),
"[project]/src/config/theme/themes/contractNest.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

// src/config/theme/themes/contractNest.ts
__turbopack_context__.s([
    "ContractNestTheme",
    ()=>ContractNestTheme
]);
const ContractNestTheme = {
    id: 'contract-nest',
    name: 'Contract Nest',
    colors: {
        brand: {
            primary: '#E53E3E',
            secondary: '#000000',
            tertiary: '#757575',
            alternate: '#F5F5F5'
        },
        utility: {
            primaryText: '#000000',
            secondaryText: '#525252',
            primaryBackground: '#FFFFFF',
            secondaryBackground: '#F5F5F5'
        },
        accent: {
            accent1: '#E53E3E',
            accent2: '#000000',
            accent3: '#BBBBBB',
            accent4: '#F0F0F0'
        },
        semantic: {
            success: '#2E7D32',
            error: '#E53E3E',
            warning: '#F57C00',
            info: '#0277BD'
        },
        surface: {
            glass: 'rgba(0,0,0,0.03)',
            glassStrong: 'rgba(0,0,0,0.05)',
            glassBorder: 'rgba(0,0,0,0.08)',
            primaryDim: 'rgba(229,62,62,0.35)',
            primaryGlow: 'rgba(229,62,62,0.1)',
            primarySubtle: 'rgba(229,62,62,0.04)'
        }
    },
    darkMode: {
        colors: {
            brand: {
                primary: '#F56565',
                secondary: '#FFFFFF',
                tertiary: '#AAAAAA',
                alternate: '#1F1F1F'
            },
            utility: {
                primaryText: '#FFFFFF',
                secondaryText: '#BBBBBB',
                primaryBackground: '#000000',
                secondaryBackground: '#1F1F1F'
            },
            accent: {
                accent1: '#FF6B6B',
                accent2: '#FFFFFF',
                accent3: '#888888',
                accent4: '#333333'
            },
            semantic: {
                success: '#66BB6A',
                error: '#EF5350',
                warning: '#FFA726',
                info: '#42A5F5'
            },
            surface: {
                glass: 'rgba(255,255,255,0.04)',
                glassStrong: 'rgba(255,255,255,0.07)',
                glassBorder: 'rgba(255,255,255,0.08)',
                primaryDim: 'rgba(245,101,101,0.4)',
                primaryGlow: 'rgba(245,101,101,0.15)',
                primarySubtle: 'rgba(245,101,101,0.06)'
            }
        }
    }
};
}),
"[project]/src/config/theme/themes/modernBold.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

// src/config/theme/themes/modernBold.ts
__turbopack_context__.s([
    "ModernBoldTheme",
    ()=>ModernBoldTheme
]);
const ModernBoldTheme = {
    id: 'modern-bold',
    name: 'Modern & Bold',
    colors: {
        brand: {
            primary: '#19db8a',
            secondary: '#38b4ff',
            tertiary: '#ffa130',
            alternate: '#e0a3e7'
        },
        utility: {
            primaryText: '#14181b',
            secondaryText: '#576c36',
            primaryBackground: '#f1f4f8',
            secondaryBackground: '#ffffff'
        },
        accent: {
            accent1: '#4c19db8a',
            accent2: '#4438b4ff',
            accent3: '#44ffa130',
            accent4: '#b2ffffff'
        },
        semantic: {
            success: '#16b070',
            error: '#ff6973',
            warning: '#cc8a30',
            info: '#38b4ff'
        },
        surface: {
            glass: 'rgba(0,0,0,0.03)',
            glassStrong: 'rgba(0,0,0,0.05)',
            glassBorder: 'rgba(0,0,0,0.08)',
            primaryDim: 'rgba(25,219,138,0.35)',
            primaryGlow: 'rgba(25,219,138,0.1)',
            primarySubtle: 'rgba(25,219,138,0.04)'
        }
    },
    darkMode: {
        colors: {
            brand: {
                primary: '#19db8a',
                secondary: '#38b4ff',
                tertiary: '#ffa130',
                alternate: '#2b32db'
            },
            utility: {
                primaryText: '#ffffff',
                secondaryText: '#95a1ac',
                primaryBackground: '#14181b',
                secondaryBackground: '#1a2429'
            },
            accent: {
                accent1: '#4c19db8a',
                accent2: '#4438b4ff',
                accent3: '#4cffa130',
                accent4: '#b214181b'
            },
            semantic: {
                success: '#16b070',
                error: '#ff6973',
                warning: '#cc6b30',
                info: '#38b4ff'
            },
            surface: {
                glass: 'rgba(255,255,255,0.04)',
                glassStrong: 'rgba(255,255,255,0.07)',
                glassBorder: 'rgba(255,255,255,0.08)',
                primaryDim: 'rgba(25,219,138,0.4)',
                primaryGlow: 'rgba(25,219,138,0.15)',
                primarySubtle: 'rgba(25,219,138,0.06)'
            }
        }
    }
};
}),
"[project]/src/config/theme/themes/modernBusiness.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

// src/config/theme/themes/modernBusiness.ts
__turbopack_context__.s([
    "ModernBusinessTheme",
    ()=>ModernBusinessTheme
]);
const ModernBusinessTheme = {
    id: 'modern-business',
    name: 'Modern Business',
    colors: {
        brand: {
            primary: '#39d2c0',
            secondary: '#1aaa99',
            tertiary: '#ee8b60',
            alternate: '#dfe3e7'
        },
        utility: {
            primaryText: '#1a1f24',
            secondaryText: '#656a85',
            primaryBackground: '#f1f4f8',
            secondaryBackground: '#ffffff'
        },
        accent: {
            accent1: '#4c39d2c0',
            accent2: '#4d1aaa99',
            accent3: '#4cee8b60',
            accent4: '#b2ffffff'
        },
        semantic: {
            success: '#165070',
            error: '#c44454',
            warning: '#cc8e30',
            info: '#39d2c0'
        },
        surface: {
            glass: 'rgba(0,0,0,0.03)',
            glassStrong: 'rgba(0,0,0,0.05)',
            glassBorder: 'rgba(0,0,0,0.08)',
            primaryDim: 'rgba(57,210,192,0.35)',
            primaryGlow: 'rgba(57,210,192,0.1)',
            primarySubtle: 'rgba(57,210,192,0.04)'
        }
    },
    darkMode: {
        colors: {
            brand: {
                primary: '#39d2c0',
                secondary: '#1aaa99',
                tertiary: '#ee8b60',
                alternate: '#2b3238'
            },
            utility: {
                primaryText: '#ffffff',
                secondaryText: '#95a1ac',
                primaryBackground: '#1a1f24',
                secondaryBackground: '#12161b'
            },
            accent: {
                accent1: '#4c39d2c0',
                accent2: '#4d1aaa99',
                accent3: '#4cee8b60',
                accent4: '#b32b3238'
            },
            semantic: {
                success: '#165070',
                error: '#c44454',
                warning: '#cc8e30',
                info: '#39d2c0'
            },
            surface: {
                glass: 'rgba(255,255,255,0.04)',
                glassStrong: 'rgba(255,255,255,0.07)',
                glassBorder: 'rgba(255,255,255,0.08)',
                primaryDim: 'rgba(57,210,192,0.4)',
                primaryGlow: 'rgba(57,210,192,0.15)',
                primarySubtle: 'rgba(57,210,192,0.06)'
            }
        }
    }
};
}),
"[project]/src/config/theme/themes/professionalRedefined.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

// src/config/theme/themes/professionalRedefined.ts
__turbopack_context__.s([
    "ProfessionalRedefinedTheme",
    ()=>ProfessionalRedefinedTheme
]);
const ProfessionalRedefinedTheme = {
    id: 'professional-redefined',
    name: 'Professional Redefined',
    colors: {
        brand: {
            primary: '#507583',
            secondary: '#18aa99',
            tertiary: '#928163',
            alternate: '#ede8df'
        },
        utility: {
            primaryText: '#101518',
            secondaryText: '#576363',
            primaryBackground: '#f1f4f8',
            secondaryBackground: '#ffffff'
        },
        accent: {
            accent1: '#4c507583',
            accent2: '#4c18aa99',
            accent3: '#4c928163',
            accent4: '#b2ffffff'
        },
        semantic: {
            success: '#16857b',
            error: '#c44454',
            warning: '#f3c344',
            info: '#507583'
        },
        surface: {
            glass: 'rgba(0,0,0,0.03)',
            glassStrong: 'rgba(0,0,0,0.05)',
            glassBorder: 'rgba(0,0,0,0.08)',
            primaryDim: 'rgba(80,117,131,0.35)',
            primaryGlow: 'rgba(80,117,131,0.1)',
            primarySubtle: 'rgba(80,117,131,0.04)'
        }
    },
    darkMode: {
        colors: {
            brand: {
                primary: '#507583',
                secondary: '#18aa99',
                tertiary: '#928163',
                alternate: '#2f2b26'
            },
            utility: {
                primaryText: '#ffffff',
                secondaryText: '#95a1ac',
                primaryBackground: '#101518',
                secondaryBackground: '#181c1f'
            },
            accent: {
                accent1: '#4c507583',
                accent2: '#4c18aa99',
                accent3: '#4c928163',
                accent4: '#b32f2b26'
            },
            semantic: {
                success: '#16857b',
                error: '#c44454',
                warning: '#f3c344',
                info: '#507583'
            },
            surface: {
                glass: 'rgba(255,255,255,0.04)',
                glassStrong: 'rgba(255,255,255,0.07)',
                glassBorder: 'rgba(255,255,255,0.08)',
                primaryDim: 'rgba(80,117,131,0.4)',
                primaryGlow: 'rgba(80,117,131,0.15)',
                primarySubtle: 'rgba(80,117,131,0.06)'
            }
        }
    }
};
}),
"[project]/src/config/theme/themes/purpleToneTheme.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "PurpleToneTheme",
    ()=>PurpleToneTheme
]);
const PurpleToneTheme = {
    id: 'purple-tone',
    name: 'Purple Tone',
    colors: {
        brand: {
            primary: '#6f61ef',
            secondary: '#392d2c',
            tertiary: '#984bb6',
            alternate: '#e0e3e7'
        },
        utility: {
            primaryText: '#151616',
            secondaryText: '#606e85',
            primaryBackground: '#f1f4f8',
            secondaryBackground: '#ffffff'
        },
        accent: {
            accent1: '#4d9489f5',
            accent2: '#4d392d2c',
            accent3: '#4d6469f5',
            accent4: '#b2ffffff'
        },
        semantic: {
            success: '#24a891',
            error: '#ff5963',
            warning: '#fcdc0c',
            info: '#ffffff'
        },
        surface: {
            glass: 'rgba(0,0,0,0.03)',
            glassStrong: 'rgba(0,0,0,0.05)',
            glassBorder: 'rgba(0,0,0,0.08)',
            primaryDim: 'rgba(111,97,239,0.35)',
            primaryGlow: 'rgba(111,97,239,0.1)',
            primarySubtle: 'rgba(111,97,239,0.04)'
        }
    },
    darkMode: {
        colors: {
            brand: {
                primary: '#6f61ef',
                secondary: '#392d2c0',
                tertiary: '#9984bb6',
                alternate: '#313442'
            },
            utility: {
                primaryText: '#ffffff',
                secondaryText: '#95a1ac',
                primaryBackground: '#151616',
                secondaryBackground: '#1a1f24'
            },
            accent: {
                accent1: '#4d9489f5',
                accent2: '#4d392d2c0',
                accent3: '#4d6469f5',
                accent4: '#b3313442'
            },
            semantic: {
                success: '#24a891',
                error: '#ff5963',
                warning: '#fcdc0c',
                info: '#ffffff'
            },
            surface: {
                glass: 'rgba(255,255,255,0.04)',
                glassStrong: 'rgba(255,255,255,0.07)',
                glassBorder: 'rgba(255,255,255,0.08)',
                primaryDim: 'rgba(111,97,239,0.4)',
                primaryGlow: 'rgba(111,97,239,0.15)',
                primarySubtle: 'rgba(111,97,239,0.06)'
            }
        }
    }
};
}),
"[project]/src/config/theme/themes/sleekCool.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

// src/config/theme/themes/sleekCool.ts
__turbopack_context__.s([
    "SleekCoolTheme",
    ()=>SleekCoolTheme
]);
const SleekCoolTheme = {
    id: 'sleek-cool',
    name: 'Sleek & Cool',
    colors: {
        brand: {
            primary: '#2797ff',
            secondary: '#8ac7ff',
            tertiary: '#acc420',
            alternate: '#e0e3e7'
        },
        utility: {
            primaryText: '#121518',
            secondaryText: '#636f81',
            primaryBackground: '#f1f4f8',
            secondaryBackground: '#ffffff'
        },
        accent: {
            accent1: '#4c2797ff',
            accent2: '#4c8ac7ff',
            accent3: '#4cacc420',
            accent4: '#b2ffffff'
        },
        semantic: {
            success: '#27ae52',
            error: '#e44444',
            warning: '#c96446',
            info: '#2797ff'
        },
        surface: {
            glass: 'rgba(0,0,0,0.03)',
            glassStrong: 'rgba(0,0,0,0.05)',
            glassBorder: 'rgba(0,0,0,0.08)',
            primaryDim: 'rgba(39,151,255,0.35)',
            primaryGlow: 'rgba(39,151,255,0.1)',
            primarySubtle: 'rgba(39,151,255,0.04)'
        }
    },
    darkMode: {
        colors: {
            brand: {
                primary: '#2797ff',
                secondary: '#8ac7ff',
                tertiary: '#acc420',
                alternate: '#212836'
            },
            utility: {
                primaryText: '#ffffff',
                secondaryText: '#919eab',
                primaryBackground: '#121518',
                secondaryBackground: '#1a1d24'
            },
            accent: {
                accent1: '#4c2797ff',
                accent2: '#4c8ac7ff',
                accent3: '#4cacc420',
                accent4: '#b3212836'
            },
            semantic: {
                success: '#27ae52',
                error: '#e44444',
                warning: '#c96446',
                info: '#2797ff'
            },
            surface: {
                glass: 'rgba(255,255,255,0.04)',
                glassStrong: 'rgba(255,255,255,0.07)',
                glassBorder: 'rgba(255,255,255,0.08)',
                primaryDim: 'rgba(39,151,255,0.4)',
                primaryGlow: 'rgba(39,151,255,0.15)',
                primarySubtle: 'rgba(39,151,255,0.06)'
            }
        }
    }
};
}),
"[project]/src/config/theme/themes/techAI.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

// src/config/theme/themes/techAI.ts
__turbopack_context__.s([
    "TechAITheme",
    ()=>TechAITheme
]);
const TechAITheme = {
    id: 'tech-ai',
    name: 'Tech AI',
    colors: {
        brand: {
            primary: '#06d5cd',
            secondary: '#18aa99',
            tertiary: '#984bb6',
            alternate: '#dfedec'
        },
        utility: {
            primaryText: '#101518',
            secondaryText: '#5763cc',
            primaryBackground: '#f1f4f8',
            secondaryBackground: '#ffffff'
        },
        accent: {
            accent1: '#4c06d5cd',
            accent2: '#4d18aa99',
            accent3: '#4d984bb6',
            accent4: '#b2ffffff'
        },
        semantic: {
            success: '#16857b',
            error: '#c4454d',
            warning: '#f3c344',
            info: '#06d5cd'
        },
        surface: {
            glass: 'rgba(0,0,0,0.03)',
            glassStrong: 'rgba(0,0,0,0.05)',
            glassBorder: 'rgba(0,0,0,0.08)',
            primaryDim: 'rgba(6,213,205,0.35)',
            primaryGlow: 'rgba(6,213,205,0.1)',
            primarySubtle: 'rgba(6,213,205,0.04)'
        }
    },
    darkMode: {
        colors: {
            brand: {
                primary: '#06d5cd',
                secondary: '#18aa99',
                tertiary: '#9984bb6',
                alternate: '#293d42'
            },
            utility: {
                primaryText: '#ffffff',
                secondaryText: '#95a1ac',
                primaryBackground: '#132121',
                secondaryBackground: '#101818'
            },
            accent: {
                accent1: '#4c06d5cd',
                accent2: '#4d18aa99',
                accent3: '#4d984bb6',
                accent4: '#b31d2428'
            },
            semantic: {
                success: '#16857b',
                error: '#c4454d',
                warning: '#f3c344',
                info: '#06d5cd'
            },
            surface: {
                glass: 'rgba(255,255,255,0.04)',
                glassStrong: 'rgba(255,255,255,0.07)',
                glassBorder: 'rgba(255,255,255,0.08)',
                primaryDim: 'rgba(6,213,205,0.4)',
                primaryGlow: 'rgba(6,213,205,0.15)',
                primarySubtle: 'rgba(6,213,205,0.06)'
            }
        }
    }
};
}),
"[project]/src/config/theme/themes/techFuture.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

// src/config/theme/themes/techFuture.ts
__turbopack_context__.s([
    "TechFutureTheme",
    ()=>TechFutureTheme
]);
const TechFutureTheme = {
    id: 'tech-future',
    name: 'Tech Future',
    colors: {
        brand: {
            primary: '#2797ff',
            secondary: '#0b67bc',
            tertiary: '#acc420',
            alternate: '#e0e3e7'
        },
        utility: {
            primaryText: '#161624',
            secondaryText: '#636f81',
            primaryBackground: '#f1f4f8',
            secondaryBackground: '#ffffff'
        },
        accent: {
            accent1: '#4c2797ff',
            accent2: '#4c0b67bc',
            accent3: '#4cacc420',
            accent4: '#b2ffffff'
        },
        semantic: {
            success: '#27a852',
            error: '#e74444',
            warning: '#c96446',
            info: '#2797ff'
        },
        surface: {
            glass: 'rgba(0,0,0,0.03)',
            glassStrong: 'rgba(0,0,0,0.05)',
            glassBorder: 'rgba(0,0,0,0.08)',
            primaryDim: 'rgba(39,151,255,0.35)',
            primaryGlow: 'rgba(39,151,255,0.1)',
            primarySubtle: 'rgba(39,151,255,0.04)'
        }
    },
    darkMode: {
        colors: {
            brand: {
                primary: '#2797ff',
                secondary: '#0b67bc',
                tertiary: '#acc420',
                alternate: '#212836'
            },
            utility: {
                primaryText: '#ffffff',
                secondaryText: '#919eab',
                primaryBackground: '#161624',
                secondaryBackground: '#1d1d2d'
            },
            accent: {
                accent1: '#4c2797ff',
                accent2: '#4c0b67bc',
                accent3: '#4cacc420',
                accent4: '#b3212836'
            },
            semantic: {
                success: '#27a852',
                error: '#e74444',
                warning: '#c96446',
                info: '#2797ff'
            },
            surface: {
                glass: 'rgba(255,255,255,0.04)',
                glassStrong: 'rgba(255,255,255,0.07)',
                glassBorder: 'rgba(255,255,255,0.08)',
                primaryDim: 'rgba(39,151,255,0.4)',
                primaryGlow: 'rgba(39,151,255,0.15)',
                primarySubtle: 'rgba(39,151,255,0.06)'
            }
        }
    }
};
}),
"[project]/src/config/theme/themes/techySimple.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

// src/config/theme/themes/techySimple.ts
__turbopack_context__.s([
    "TechySimpleTheme",
    ()=>TechySimpleTheme
]);
const TechySimpleTheme = {
    id: 'techy-simple',
    name: 'Techy Simple',
    colors: {
        brand: {
            primary: '#f83b46',
            secondary: '#ff6a73',
            tertiary: '#0299ff',
            alternate: '#e0e3e7'
        },
        utility: {
            primaryText: '#141518',
            secondaryText: '#677681',
            primaryBackground: '#f1f4f8',
            secondaryBackground: '#ffffff'
        },
        accent: {
            accent1: '#4cf83b46',
            accent2: '#4cff6a73',
            accent3: '#4c0299ff',
            accent4: '#b2ffffff'
        },
        semantic: {
            success: '#6bbd78',
            error: '#ff5963',
            warning: '#ec9c4b',
            info: '#0299ff'
        },
        surface: {
            glass: 'rgba(0,0,0,0.03)',
            glassStrong: 'rgba(0,0,0,0.05)',
            glassBorder: 'rgba(0,0,0,0.08)',
            primaryDim: 'rgba(248,59,70,0.35)',
            primaryGlow: 'rgba(248,59,70,0.1)',
            primarySubtle: 'rgba(248,59,70,0.04)'
        }
    },
    darkMode: {
        colors: {
            brand: {
                primary: '#f83b46',
                secondary: '#ff6a73',
                tertiary: '#0299ff',
                alternate: '#262b36'
            },
            utility: {
                primaryText: '#ffffff',
                secondaryText: '#95a1ac',
                primaryBackground: '#141518',
                secondaryBackground: '#1a1f24'
            },
            accent: {
                accent1: '#4cf83b46',
                accent2: '#4cff6a73',
                accent3: '#4c0299ff',
                accent4: '#b3262b36'
            },
            semantic: {
                success: '#6bbd78',
                error: '#ff5963',
                warning: '#ec9c4b',
                info: '#0299ff'
            },
            surface: {
                glass: 'rgba(255,255,255,0.04)',
                glassStrong: 'rgba(255,255,255,0.07)',
                glassBorder: 'rgba(255,255,255,0.08)',
                primaryDim: 'rgba(248,59,70,0.4)',
                primaryGlow: 'rgba(248,59,70,0.15)',
                primarySubtle: 'rgba(248,59,70,0.06)'
            }
        }
    }
};
}),
"[project]/src/config/theme/themes/vikunaBlack.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "VikunaBlackTheme",
    ()=>VikunaBlackTheme
]);
const VikunaBlackTheme = {
    id: 'vikuna-black',
    name: 'Vikuna Black',
    colors: {
        brand: {
            primary: '#B8942F',
            secondary: '#1A1A1F',
            tertiary: '#6B6555',
            alternate: '#F5F2EB'
        },
        utility: {
            primaryText: '#1A1A1F',
            secondaryText: 'rgba(26,26,31,0.6)',
            primaryBackground: '#F5F2EB',
            secondaryBackground: '#EDE9E0'
        },
        accent: {
            accent1: '#4A8FD4',
            accent2: '#3BAFA7',
            accent3: '#D47070',
            accent4: '#7A6FD4'
        },
        semantic: {
            success: '#3BAFA7',
            error: '#D47070',
            warning: '#D4911E',
            info: '#4A8FD4'
        },
        surface: {
            glass: 'rgba(0,0,0,0.03)',
            glassStrong: 'rgba(0,0,0,0.05)',
            glassBorder: 'rgba(0,0,0,0.08)',
            primaryDim: 'rgba(184,148,47,0.35)',
            primaryGlow: 'rgba(184,148,47,0.1)',
            primarySubtle: 'rgba(184,148,47,0.04)'
        }
    },
    darkMode: {
        colors: {
            brand: {
                primary: '#C9A84C',
                secondary: '#F0ECE2',
                tertiary: '#3A3F52',
                alternate: '#111118'
            },
            utility: {
                primaryText: '#F0ECE2',
                secondaryText: 'rgba(240,236,226,0.6)',
                primaryBackground: '#0A0A0F',
                secondaryBackground: '#111118'
            },
            accent: {
                accent1: '#5EAAF0',
                accent2: '#4ECDC4',
                accent3: '#E88B8B',
                accent4: '#9B8FE8'
            },
            semantic: {
                success: '#4ECDC4',
                error: '#E88B8B',
                warning: '#E8B44C',
                info: '#5EAAF0'
            },
            surface: {
                glass: 'rgba(255,255,255,0.04)',
                glassStrong: 'rgba(255,255,255,0.07)',
                glassBorder: 'rgba(255,255,255,0.08)',
                primaryDim: 'rgba(201,168,76,0.4)',
                primaryGlow: 'rgba(201,168,76,0.15)',
                primarySubtle: 'rgba(201,168,76,0.06)'
            }
        }
    }
};
}),
"[project]/src/config/theme/registry.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "defaultTheme",
    ()=>defaultTheme,
    "getAllThemes",
    ()=>getAllThemes,
    "getTheme",
    ()=>getTheme,
    "themes",
    ()=>themes
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$config$2f$theme$2f$themes$2f$bharathavarshaTheme$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/config/theme/themes/bharathavarshaTheme.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$config$2f$theme$2f$themes$2f$classicElegantTheme$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/config/theme/themes/classicElegantTheme.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$config$2f$theme$2f$themes$2f$contractNest$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/config/theme/themes/contractNest.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$config$2f$theme$2f$themes$2f$modernBold$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/config/theme/themes/modernBold.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$config$2f$theme$2f$themes$2f$modernBusiness$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/config/theme/themes/modernBusiness.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$config$2f$theme$2f$themes$2f$professionalRedefined$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/config/theme/themes/professionalRedefined.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$config$2f$theme$2f$themes$2f$purpleToneTheme$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/config/theme/themes/purpleToneTheme.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$config$2f$theme$2f$themes$2f$sleekCool$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/config/theme/themes/sleekCool.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$config$2f$theme$2f$themes$2f$techAI$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/config/theme/themes/techAI.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$config$2f$theme$2f$themes$2f$techFuture$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/config/theme/themes/techFuture.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$config$2f$theme$2f$themes$2f$techySimple$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/config/theme/themes/techySimple.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$config$2f$theme$2f$themes$2f$vikunaBlack$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/config/theme/themes/vikunaBlack.ts [app-rsc] (ecmascript)");
;
;
;
;
;
;
;
;
;
;
;
;
const themes = [
    __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$config$2f$theme$2f$themes$2f$vikunaBlack$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["VikunaBlackTheme"],
    __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$config$2f$theme$2f$themes$2f$classicElegantTheme$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["ClassicElegantTheme"],
    __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$config$2f$theme$2f$themes$2f$purpleToneTheme$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["PurpleToneTheme"],
    __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$config$2f$theme$2f$themes$2f$bharathavarshaTheme$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["BharathaVarshaTheme"],
    __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$config$2f$theme$2f$themes$2f$contractNest$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["ContractNestTheme"],
    __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$config$2f$theme$2f$themes$2f$modernBold$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["ModernBoldTheme"],
    __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$config$2f$theme$2f$themes$2f$modernBusiness$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["ModernBusinessTheme"],
    __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$config$2f$theme$2f$themes$2f$professionalRedefined$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["ProfessionalRedefinedTheme"],
    __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$config$2f$theme$2f$themes$2f$sleekCool$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["SleekCoolTheme"],
    __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$config$2f$theme$2f$themes$2f$techAI$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["TechAITheme"],
    __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$config$2f$theme$2f$themes$2f$techFuture$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["TechFutureTheme"],
    __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$config$2f$theme$2f$themes$2f$techySimple$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["TechySimpleTheme"]
];
const defaultTheme = __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$config$2f$theme$2f$themes$2f$vikunaBlack$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["VikunaBlackTheme"];
function getTheme(id) {
    return themes.find((t)=>t.id === id) || defaultTheme;
}
function getAllThemes() {
    return themes.map((t)=>({
            id: t.id,
            name: t.name
        }));
}
}),
"[project]/src/config/theme/index.ts [app-rsc] (ecmascript) <locals>", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([]);
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$config$2f$theme$2f$ThemeProvider$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/config/theme/ThemeProvider.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$config$2f$theme$2f$registry$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/config/theme/registry.ts [app-rsc] (ecmascript)");
;
;
}),
"[project]/src/app/layout.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>RootLayout,
    "metadata",
    ()=>metadata
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$config$2f$theme$2f$index$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$locals$3e$__ = __turbopack_context__.i("[project]/src/config/theme/index.ts [app-rsc] (ecmascript) <locals>");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$config$2f$theme$2f$ThemeProvider$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/config/theme/ThemeProvider.tsx [app-rsc] (ecmascript)");
;
;
const metadata = {
    title: 'ProessionalKey',
    description: 'Financial Advisory Platform for MFDs'
};
function RootLayout({ children }) {
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("html", {
        lang: "en",
        children: [
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("head", {
                children: [
                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("link", {
                        rel: "stylesheet",
                        href: "https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;500;600;700&family=DM+Sans:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap"
                    }, void 0, false, {
                        fileName: "[project]/src/app/layout.tsx",
                        lineNumber: 14,
                        columnNumber: 9
                    }, this),
                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("style", {
                        dangerouslySetInnerHTML: {
                            __html: `
          :root {
            --font-display: 'Playfair Display', Georgia, serif;
            --font-body: 'DM Sans', system-ui, sans-serif;
            --font-mono: 'JetBrains Mono', monospace;
          }
        `
                        }
                    }, void 0, false, {
                        fileName: "[project]/src/app/layout.tsx",
                        lineNumber: 18,
                        columnNumber: 9
                    }, this)
                ]
            }, void 0, true, {
                fileName: "[project]/src/app/layout.tsx",
                lineNumber: 11,
                columnNumber: 7
            }, this),
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("body", {
                style: {
                    margin: 0,
                    padding: 0
                },
                children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$config$2f$theme$2f$ThemeProvider$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["ThemeProvider"], {
                    defaultThemeId: ("TURBOPACK compile-time value", "vikuna-black") || 'vikuna-black',
                    children: children
                }, void 0, false, {
                    fileName: "[project]/src/app/layout.tsx",
                    lineNumber: 27,
                    columnNumber: 9
                }, this)
            }, void 0, false, {
                fileName: "[project]/src/app/layout.tsx",
                lineNumber: 26,
                columnNumber: 7
            }, this)
        ]
    }, void 0, true, {
        fileName: "[project]/src/app/layout.tsx",
        lineNumber: 10,
        columnNumber: 5
    }, this);
}
}),
"[project]/src/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/src/app/layout.tsx [app-rsc] (ecmascript)"));
}),
"[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)", ((__turbopack_context__, module, exports) => {
"use strict";

module.exports = __turbopack_context__.r("[project]/node_modules/next/dist/server/route-modules/app-page/module.compiled.js [app-rsc] (ecmascript)").vendored['react-rsc'].ReactJsxDevRuntime;
}),
];

//# sourceMappingURL=_0~y5fbd._.js.map